services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        ports:
            - '5173:5173'
        labels:
            # Frontend
            - "traefik.enable=true"
            - "traefik.http.routers.core-test-r.rule=Host(`test.medicco.local`)"
            - 'traefik.http.routers.core-test-r.entrypoints=web'
            #            - 'traefik.http.routers.core-test-r.tls=true'
            #            - 'traefik.http.routers.core-test-r.tls.certresolver=localresolver'
            - "traefik.http.services.core-test-s.loadbalancer.server.port=80"
            - "traefik.http.routers.core-test-r.service=core-test-s"
            # Vite
        #            - "traefik.http.routers.core-test-vite-r.rule=Host(`test.medicco.local`)"
        #            - 'traefik.http.routers.core-test-vite-r.entrypoints=vite'
        #            - "traefik.http.services.core-test-vite-s.loadbalancer.server.port=5173"
        #            - "traefik.http.routers.core-test-vite-r.service=core-test-vite-s"
        networks:
            - sail
            - traefik-dev
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
    traefik-dev:
        external: true
volumes:
    sail-mysql:
        driver: local
